apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-us-aesthetic
  labels:
    type: local
spec:
  storageClassName: local-storage
  capacity:
    storage: 10Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  local:
    path: /home/azgartaj/Smrutaj/pv-local
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
          - key: kubernetes.io/hostname
            operator: Exists