apiVersion: apps/v1
kind: Deployment
metadata:
  name: us-aesthetic-storyservice-deployment
  labels:
    app: us-aesthetic-storyservice
spec:
  replicas: 1
  selector:
    matchLabels:
      app: us-aesthetic-storyservice
  template:
    metadata:
      labels:
        app: us-aesthetic-storyservice
    spec:
      containers:
      - name: us-aesthetic-storyservice-container
        image: localhost:32000/us-aesthetic-storyservice
        ports:
        - containerPort: 8080
        resources:
          limits:
            cpu: "0.2"
            memory: "128Mi"
          requests:
            cpu: "0.2"
            memory: "128Mi"
        env:
        - name: PORT
          value: "8080"
        - name: MONGO_USERNAME
          valueFrom:
            secretKeyRef:
              name: mongo-credentials
              key: mongo-username
        - name: MONGO_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mongo-credentials
              key: mongo-password
        - name: MONGO_CLUSTER
          valueFrom:
            secretKeyRef:
              name: mongo-credentials
              key: mongo-cluster
