services:
  us-images-go:
    build:
      context: ./image_server
      tags:
        - abtaj.azurecr.io/us-aesthetic-images
    image: abtaj.azurecr.io/us-aesthetic-images

  us-frontend:
    build:
      context: ./frontend
      tags:
        - abtaj.azurecr.io/us-aesthetic-frontend
    image: abtaj.azurecr.io/us-aesthetic-frontend

  us-backend-go:
    build:
      context: ./backend
      tags:
        - abtaj.azurecr.io/us-aesthetic-storyservice
    image: abtaj.azurecr.io/us-aesthetic-storyservice

  us-auth-service:
    build:
      context: ./auth-service
      tags:
        - abtaj.azurecr.io/us-aesthetic-authservice
    image: abtaj.azurecr.io/us-aesthetic-authservice
