services:
  us-images-go:
    build:
      context: ./image_server
      tags:
        - localhost:32000/us-aesthetic-images
    image: localhost:32000/us-aesthetic-images

  us-frontend:
    build:
      context: ./frontend
      tags:
        - localhost:32000/us-aesthetic-frontend
    image: localhost:32000/us-aesthetic-frontend

  us-backend-go:
    build:
      context: ./backend
      tags:
        - localhost:32000/us-aesthetic-storyservice
    image: localhost:32000/us-aesthetic-storyservice
