apiVersion: apps/v1
kind: Deployment
metadata:
  name: us-aesthetic-frontend-deployment
  labels:
    app: us-aesthetic-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: us-aesthetic-frontend
  template:
    metadata:
      labels:
        app: us-aesthetic-frontend
    spec:
      containers:
      - name: us-aesthetic-frontend-container
        image: localhost:32000/us-aesthetic-frontend
        ports:
        - containerPort: 8080
        resources:
          limits:
            cpu: "0.5"
            memory: "512Mi"
          requests:
            cpu: "0.5"
            memory: "256Mi"
        env:
        - name: PORT
          value: "8080"
        - name: GENERATE_SOURCEMAP
          value: "false"
