apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.frontend.name }}-app
spec:
  selector:
    app: {{ .Values.frontend.name }}
  ports:
  - port: {{ .Values.frontend.port }}
    targetPort: {{ .Values.frontend.port }}