apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Values.imageService.name }}-ingress
spec:
  rules:
    - host: {{ .Values.imageService.url }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ .Values.imageService.name }}-app
                port:
                  number: {{ .Values.imageService.port }}