apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Values.backend.name }}-ingress
spec:
  rules:
    - host: {{ .Values.backend.url }}
      http:
        paths:
          - path: {{ .Values.backend.servicePath }}
            pathType: Prefix
            backend:
              service:
                name: {{ .Values.backend.name }}-app
                port:
                  number: 8080