apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ .Values.storage.persistentVolume.name }}
  labels:
    type: local
spec:
  storageClassName: {{ .Values.storage.storageClass.name }}
  capacity:
    storage: 10Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  local:
    path: {{ .Values.storage.persistentVolume.localPath }}
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
          - key: kubernetes.io/hostname
            operator: Exists