apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.frontend.name }}-deployment
  labels:
    app: {{ .Values.frontend.name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.frontend.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.frontend.name }}
    spec:
      containers:
      - name: {{ .Values.frontend.name }}-container
        image: localhost:32000/{{ .Values.frontend.name }}
        ports:
        - containerPort: {{ .Values.frontend.port }}
        resources:
          limits:
            cpu: "0.2"
            memory: "128Mi"
          requests:
            cpu: "0.2"
            memory: "128Mi"
        env:
        - name: PORT
          value: {{ .Values.frontend.port | quote}}
        - name: GENERATE_SOURCEMAP
          value: "false"
