apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.authService.name }}-deployment
  labels:
    app: {{ .Values.authService.name }}
spec:
  replicas: {{ .Values.authService.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.authService.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.authService.name }}
    spec:
      containers:
      - name: {{ .Values.authService.name }}-container
        image: {{ .Values.containerRegistry }}/{{ .Values.authService.name }}
        imagePullPolicy: Always
        ports:
        - containerPort: {{ .Values.authService.port }}
        resources:
          limits:
            cpu: "100m"
            memory: "128Mi"
          requests:
            cpu: "100m"
            memory: "128Mi"
        env:
        - name: PORT
          value: "{{ .Values.authService.port }}"
        - name: MONGO_USERNAME
          valueFrom:
            secretKeyRef:
              name: mongo-credentials
              key: mongo-username
        - name: MONGO_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mongo-credentials
              key: mongo-password
        - name: MONGO_CLUSTER
          valueFrom:
            secretKeyRef:
              name: mongo-credentials
              key: mongo-cluster
        - name: JWT_SECRET
          valueFrom:
            secretKeyRef:
              name: mongo-credentials
              key: jwt-secret