apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.authService.name }}-app
spec:
  selector:
    app: {{ .Values.authService.name }}
  ports:
  - port: {{ .Values.authService.port }}
    targetPort: {{ .Values.authService.port }}