apiVersion: v1
kind: PersistentVolume
metadata:
  annotations:
    pv.kubernetes.io/provisioned-by: disk.csi.azure.com
  name: {{ .Values.storage.persistentVolume.name }}
spec:
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: {{ .Values.storage.storageClass.name }}
  csi:
    driver: disk.csi.azure.com
    volumeHandle: {{ .Values.storage.persistentVolume.diskResourceId }}
    volumeAttributes:
      fsType: ext4