apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.backend.name }}-app
spec:
  selector:
    app: {{ .Values.backend.name }}
  ports:
  - port: {{ .Values.backend.port }}
    targetPort: {{ .Values.backend.port }}