apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.imageService.name }}-app
spec:
  selector:
    app: {{ .Values.imageService.name }}
  ports:
  - port: {{ .Values.imageService.port }}
    targetPort: {{ .Values.imageService.port }}