containerRegistry: localhost:32000
imageService:
  name: us-aesthetic-images
  port: 8100
  replicas: 1
  url: images.smruthitaj.life
  volumeMount:
    name: us-aesthetic-volume
    volumeMountPath: /usr/share/us-aesthetic-volume

storage:
  storageClass:
    name: local-storage
  persistentVolume:
    name: pv-us-aesthetic
    localPath: /home/azgartaj/Smrutaj/pv-local
  persistentStorageClaim:
    name: pv-us-aesthetic-claim

frontend:
  replicas: 1
  name: us-aesthetic-frontend
  port: 8080
  url: my.smruthitaj.life

backend:
  replicas: 1
  name: us-aesthetic-storyservice
  port: 8080
  url: api.smruthitaj.life
  servicePath: /storyservice/

authService:
  replicas: 1
  name: us-aesthetic-authservice
  port: 8080
  url: auth.smruthitaj.life
  servicePath: /auth/